# Generated by Django 4.2.26 on 2025-11-21 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="客户姓名")),
                (
                    "phone",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="电话号码"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("wait_contact", "待联系"),
                            ("wait_visit", "待上门"),
                            ("visited", "已上门"),
                            ("signed", "已签约"),
                            ("no_intent", "无意向"),
                            ("unreachable", "无法联系"),
                        ],
                        default="wait_contact",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="线索来源"
                    ),
                ),
                (
                    "city_auto",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="自动定位城市"
                    ),
                ),
                (
                    "region_manual",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="手动填写地域"
                    ),
                ),
                (
                    "contact_count",
                    models.PositiveIntegerField(default=0, verbose_name="联系次数"),
                ),
                (
                    "next_contact_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="下次联系时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "last_contact_at",
                    models.DateTimeField(auto_now=True, verbose_name="最后联系时间"),
                ),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展数据"),
                ),
                (
                    "sales_rep",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="销售代表",
                    ),
                ),
            ],
            options={
                "verbose_name": "客户",
                "verbose_name_plural": "客户",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HighSeasCustomer",
            fields=[],
            options={
                "verbose_name": "公海客户",
                "verbose_name_plural": "公海客户",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("sales.customer",),
        ),
    ]
