# Generated by Django 4.2.26 on 2025-11-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="英文字母和下划线，如: custom_budget",
                        max_length=50,
                        unique=True,
                        verbose_name="字段标识符",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="显示给用户的字段名称",
                        max_length=100,
                        verbose_name="显示名称",
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "文本"),
                            ("textarea", "多行文本"),
                            ("number", "数字"),
                            ("date", "日期"),
                            ("datetime", "日期时间"),
                            ("select", "单选下拉"),
                            ("multiselect", "多选"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="字段类型",
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='格式: ["选项1", "选项2", "选项3"]',
                        verbose_name="选项配置",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="是否必填"),
                ),
                (
                    "placeholder",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="占位符文本"
                    ),
                ),
                (
                    "help_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="帮助文本"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="数字越小越靠前", verbose_name="排序"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "自定义字段",
                "verbose_name_plural": "自定义字段",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AlterField(
            model_name="customer",
            name="status",
            field=models.CharField(
                choices=[
                    ("wait_contact", "待沟通"),
                    ("wait_followup", "待跟进"),
                    ("wait_visit", "待到访"),
                    ("visited", "已到访"),
                    ("signed", "已签约"),
                    ("no_intent", "无意向"),
                    ("unreachable", "未接通"),
                ],
                default="wait_contact",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
