# Generated by Django 4.2.26 on 2025-12-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_customfield_alter_customer_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="is_key_customer",
            field=models.BooleanField(default=False, verbose_name="重点客户"),
        ),
        migrations.AddField(
            model_name="customer",
            name="notes",
            field=models.TextField(blank=True, default="", verbose_name="备注信息"),
        ),
        migrations.AddField(
            model_name="customer",
            name="province",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="省份"
            ),
        ),
    ]
